site_name: My Docs
nav:
  - Home: 'index.md'
  - Book Note:
      - Effective python: 'booknotes/effective-python.md'
      - Cleancode: 'booknotes/cleancode.md'
theme: rtd-dropdown
markdown_extensions:
  - smarty
  - toc:
      baselevel: 1
      permalink: True
